dados <- read.csv("DadosLimpos.csv")
str(dados)
names(dados)
summary(dados)
summary(dados$price)
summary(dados$minimum_nights)
summary(dados$number_of_reviews)
summary(dados$reviews_per_month)
summary(dados$availability_365)
hist(dados$price, main="Distribuição do Preço")
boxplot(dados$price, main="Boxplot do Preço")
boxplot(price ~ room_type, data=dados)
plot(dados$number_of_reviews, dados$price)
plot(dados$availability_365, dados$price)
plot(dados$minimum_nights, dados$price)
cor(dados[, c("price","minimum_nights","number_of_reviews","reviews_per_month","availability_365","calculated_host_listings_count")],use="complete.obs")
